import type { Device, DeviceCategory, ProjectConfig, Scenario } from './types'

export const scenarios: Scenario[] = [
  {
    id: 'normal',
    name: 'Praca normalna',
    description: 'Standardowa praca budynku bez skrajnych warunków pogodowych.',
  },
  {
    id: 'winter',
    name: 'Zima',
    description: 'Maksymalne obciążenie ogrzewaniem, wentylacją i instalacjami pomocniczymi.',
  },
  {
    id: 'summer',
    name: 'Lato',
    description: 'Maksymalne obciążenie klimatyzacją, chłodzeniem i wentylacją.',
  },
  {
    id: 'backup',
    name: 'Tryb rezerwowy',
    description: 'Odbiorniki krytyczne dla zasilania rezerwowego lub pracy awaryjnej.',
  },
]

export const deviceCategories: DeviceCategory[] = [
  {
    id: 'heatPumps',
    name: 'Pompy ciepła i ogrzewanie',
    defaultSimultaneityFactor: 0.9,
    defaultUtilizationFactor: 0.85,
  },
  {
    id: 'cooling',
    name: 'Klimatyzacja i chłodzenie',
    defaultSimultaneityFactor: 0.85,
    defaultUtilizationFactor: 0.8,
  },
  {
    id: 'ventilation',
    name: 'Wentylacja',
    defaultSimultaneityFactor: 0.95,
    defaultUtilizationFactor: 0.9,
  },
  {
    id: 'lighting',
    name: 'Oświetlenie',
    defaultSimultaneityFactor: 0.85,
    defaultUtilizationFactor: 0.75,
  },
  {
    id: 'sockets',
    name: 'Gniazda i drobne odbiorniki',
    defaultSimultaneityFactor: 0.45,
    defaultUtilizationFactor: 0.65,
  },
  {
    id: 'serverRoom',
    name: 'Serwerownia i IT',
    defaultSimultaneityFactor: 1,
    defaultUtilizationFactor: 0.9,
  },
  {
    id: 'energyStorage',
    name: 'Magazyn energii',
    defaultSimultaneityFactor: 1,
    defaultUtilizationFactor: 1,
  },
  {
    id: 'evChargers',
    name: 'Ładowarki EV',
    defaultSimultaneityFactor: 0.55,
    defaultUtilizationFactor: 0.8,
  },
  {
    id: 'technology',
    name: 'Technologia magazynowa',
    defaultSimultaneityFactor: 0.7,
    defaultUtilizationFactor: 0.75,
  },
  {
    id: 'other',
    name: 'Pozostałe',
    defaultSimultaneityFactor: 0.7,
    defaultUtilizationFactor: 0.75,
  },
]

export const defaultProject: ProjectConfig = {
  name: 'Budynek magazynowo-biurowy',
  buildingType: 'Magazyn z częścią biurową',
  warehouseAreaM2: 3000,
  warehouseHeightM: 8,
  officeAreaM2: 450,
  peopleCount: 35,
  computerCount: 32,
  minWarehouseTempC: 8,
  maxWarehouseTempC: 28,
  minOfficeTempC: 20,
  maxOfficeTempC: 26,
  reservePercent: 15,
  useAlternativeHeatingCooling: true,
  zones: [
    {
      id: 'warehouse',
      name: 'Magazyn',
      type: 'warehouse',
      areaM2: 3000,
      minTempC: 8,
      maxTempC: 28,
    },
    {
      id: 'office',
      name: 'Biuro',
      type: 'office',
      areaM2: 450,
      minTempC: 20,
      maxTempC: 26,
    },
    {
      id: 'server-room',
      name: 'Serwerownia',
      type: 'serverRoom',
      areaM2: 20,
      minTempC: 18,
      maxTempC: 24,
    },
    {
      id: 'technical',
      name: 'Pomieszczenia techniczne',
      type: 'technical',
      areaM2: 60,
      minTempC: 10,
      maxTempC: 30,
    },
  ],
  energyStorage: {
    enabled: true,
    capacityKwh: 120,
    chargePowerKw: 50,
    dischargePowerKw: 50,
    mode: 'peakShaving',
    roundTripEfficiencyPercent: 92,
  },
}

export const defaultDevices: Device[] = [
  {
    id: 'device-heat-pump-warehouse',
    name: 'Pompa ciepła magazynu',
    categoryId: 'heatPumps',
    zoneId: 'warehouse',
    powerInputMode: 'area',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 56,
    powerDensityWm2: 18,
    simultaneityFactor: 0.9,
    utilizationFactor: 0.85,
    cosPhi: 0.92,
    phase: '3P',
    voltageV: 400,
    scenarios: ['winter', 'normal'],
    notes: 'Zasilanie ogrzewania magazynu w okresie zimowym.',
  },
  {
    id: 'device-office-ac',
    name: 'Klimatyzacja biur',
    categoryId: 'cooling',
    zoneId: 'office',
    powerInputMode: 'area',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 21,
    powerDensityWm2: 45,
    simultaneityFactor: 0.8,
    utilizationFactor: 0.8,
    cosPhi: 0.9,
    phase: '1P',
    voltageV: 230,
    scenarios: ['summer', 'normal'],
  },
  {
    id: 'device-ahu',
    name: 'Centrale wentylacyjne',
    categoryId: 'ventilation',
    zoneId: 'technical',
    powerInputMode: 'manual',
    quantityInputMode: 'manual',
    quantity: 2,
    unitPowerKw: 12,
    simultaneityFactor: 0.95,
    utilizationFactor: 0.9,
    cosPhi: 0.88,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer', 'backup'],
  },
  {
    id: 'device-led-warehouse',
    name: 'Oświetlenie LED magazynu',
    categoryId: 'lighting',
    zoneId: 'warehouse',
    powerInputMode: 'area',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 24,
    powerDensityWm2: 8,
    simultaneityFactor: 0.85,
    utilizationFactor: 0.75,
    cosPhi: 0.95,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer', 'backup'],
  },
  {
    id: 'device-server-room',
    name: 'Serwerownia i UPS',
    categoryId: 'serverRoom',
    zoneId: 'server-room',
    powerInputMode: 'manual',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 18,
    simultaneityFactor: 1,
    utilizationFactor: 0.9,
    cosPhi: 0.95,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer', 'backup'],
  },
  {
    id: 'device-dock-equipment',
    name: 'Bramy i urządzenia dokowe',
    categoryId: 'technology',
    zoneId: 'warehouse',
    powerInputMode: 'manual',
    quantityInputMode: 'manual',
    quantity: 8,
    unitPowerKw: 1.5,
    simultaneityFactor: 0.45,
    utilizationFactor: 0.7,
    cosPhi: 0.85,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer'],
  },
  {
    id: 'device-office-computers',
    name: 'Komputery stanowiskowe',
    categoryId: 'sockets',
    zoneId: 'office',
    powerInputMode: 'manual',
    quantityInputMode: 'computers',
    quantity: 32,
    unitPowerKw: 0.18,
    simultaneityFactor: 0.8,
    utilizationFactor: 0.7,
    cosPhi: 0.95,
    phase: '1P',
    voltageV: 230,
    scenarios: ['normal', 'summer', 'backup'],
    notes: 'Ilość pobierana z parametru liczby komputerów w projekcie.',
  },
  {
    id: 'device-workstations-sockets',
    name: 'Gniazda stanowisk pracy',
    categoryId: 'sockets',
    zoneId: 'office',
    powerInputMode: 'manual',
    quantityInputMode: 'people',
    quantity: 35,
    unitPowerKw: 0.12,
    simultaneityFactor: 0.55,
    utilizationFactor: 0.65,
    cosPhi: 0.95,
    phase: '1P',
    voltageV: 230,
    scenarios: ['normal', 'summer'],
    notes: 'Ilość pobierana z parametru liczby osób pracujących.',
  },
]
