import type {
  Device,
  DeviceCategory,
  DeviceCategoryId,
  ProjectConfig,
  Scenario,
  ThermalDensityUnit,
  Zone,
} from './types'

type ZonePowerDensityDefaults = Partial<Record<DeviceCategoryId | 'default', number>>

const heatPumpThermalDensityDefaults: Record<Zone['type'], Record<ThermalDensityUnit, number>> = {
  warehouse: { Wm2: 18, Wm3: 2.25 },
  office: { Wm2: 40, Wm3: 3.5 },
  serverRoom: { Wm2: 50, Wm3: 4 },
  technical: { Wm2: 25, Wm3: 2.5 },
  common: { Wm2: 20, Wm3: 2 },
  custom: { Wm2: 20, Wm3: 2 },
}

export const getDefaultThermalDensityUnit = (zoneType: Zone['type']): ThermalDensityUnit =>
  zoneType === 'warehouse' ? 'Wm3' : 'Wm2'

export const getDefaultHeatPumpThermalDensity = (
  zoneType: Zone['type'],
  unit: ThermalDensityUnit,
): number => heatPumpThermalDensityDefaults[zoneType]?.[unit] ?? (unit === 'Wm3' ? 2.25 : 20)

/** Domyślna moc cieplna CWU na osobę [W/os.] (przy trybie „liczba osób”). */
export const defaultCwuThermalDensityWPerPerson = 350

export const zonePowerDensityDefaults: Record<Zone['type'], ZonePowerDensityDefaults> = {
  warehouse: {
    lighting: 8,
    default: 10,
  },
  office: {
    cooling: 45,
    cwu: defaultCwuThermalDensityWPerPerson,
    kitchen: 35,
    default: 40,
  },
  serverRoom: {
    cooling: 80,
    serverRoom: 90,
    default: 50,
  },
  technical: {
    ventilation: 15,
    mills: 25,
    printer3d: 15,
    default: 12,
  },
  common: {
    kitchen: 40,
    default: 12,
  },
  custom: {
    default: 10,
  },
}

/** COP w warunkach normalnych (informacyjnie). */
export const defaultHeatPumpCopNormal = 3.5
/** COP przy -20°C — do bilansu mocy przyłącza. */
export const defaultHeatPumpCopMinus20C = 1.75
/** @deprecated Użyj defaultHeatPumpCopNormal */
export const defaultHeatPumpCop = defaultHeatPumpCopNormal

export const getDefaultPowerDensityWm2 = (
  zoneType: Zone['type'],
  categoryId: DeviceCategoryId,
): number => {
  const zoneDefaults = zonePowerDensityDefaults[zoneType] ?? zonePowerDensityDefaults.custom
  return zoneDefaults[categoryId] ?? zoneDefaults.default ?? 10
}

export const scenarios: Scenario[] = [
  {
    id: 'normal',
    name: 'Praca normalna',
    description:
      'Typowa praca budynku: odbiorniki bazowe; HVAC z odniesienia do szczytów Zima/Lato (średnia lub obniżony udział), także gdy pompy i klimatyzacja nie są zaznaczone w tym wariancie.',
  },
  {
    id: 'winter',
    name: 'Zima',
    description: 'Maksymalne obciążenie ogrzewaniem, wentylacją i instalacjami pomocniczymi.',
  },
  {
    id: 'summer',
    name: 'Lato',
    description: 'Maksymalne obciążenie klimatyzacją, chłodzeniem i wentylacją.',
  },
  {
    id: 'backup',
    name: 'Tryb rezerwowy',
    description: 'Odbiorniki krytyczne dla zasilania rezerwowego lub pracy awaryjnej.',
  },
]

export const deviceCategories: DeviceCategory[] = [
  {
    id: 'heatPumps',
    name: 'Pompy ciepła i ogrzewanie',
    defaultSimultaneityFactor: 0.9,
    defaultUtilizationFactor: 0.85,
  },
  {
    id: 'cooling',
    name: 'Klimatyzacja i chłodzenie',
    defaultSimultaneityFactor: 0.85,
    defaultUtilizationFactor: 0.8,
  },
  {
    id: 'cwu',
    name: 'CWU — ciepła woda użytkowa',
    defaultSimultaneityFactor: 0.7,
    defaultUtilizationFactor: 0.65,
  },
  {
    id: 'ventilation',
    name: 'Wentylacja',
    defaultSimultaneityFactor: 0.95,
    defaultUtilizationFactor: 0.9,
  },
  {
    id: 'kitchen',
    name: 'Kuchnie',
    defaultSimultaneityFactor: 0.75,
    defaultUtilizationFactor: 0.65,
  },
  {
    id: 'lighting',
    name: 'Oświetlenie',
    defaultSimultaneityFactor: 0.85,
    defaultUtilizationFactor: 0.75,
  },
  {
    id: 'sockets',
    name: 'Gniazda i drobne odbiorniki',
    defaultSimultaneityFactor: 0.45,
    defaultUtilizationFactor: 0.65,
  },
  {
    id: 'serverRoom',
    name: 'Serwerownia i IT',
    defaultSimultaneityFactor: 1,
    defaultUtilizationFactor: 0.9,
  },
  {
    id: 'energyStorage',
    name: 'Magazyn energii',
    defaultSimultaneityFactor: 1,
    defaultUtilizationFactor: 1,
  },
  {
    id: 'evChargers',
    name: 'Ładowarki EV',
    defaultSimultaneityFactor: 0.55,
    defaultUtilizationFactor: 0.8,
  },
  {
    id: 'technology',
    name: 'Technologia magazynowa',
    defaultSimultaneityFactor: 0.7,
    defaultUtilizationFactor: 0.75,
  },
  {
    id: 'mills',
    name: 'Frezarki',
    defaultSimultaneityFactor: 0.5,
    defaultUtilizationFactor: 0.65,
  },
  {
    id: 'printer3d',
    name: 'Druk 3D',
    defaultSimultaneityFactor: 0.55,
    defaultUtilizationFactor: 0.6,
  },
  {
    id: 'other',
    name: 'Pozostałe',
    defaultSimultaneityFactor: 0.7,
    defaultUtilizationFactor: 0.75,
  },
]

export const defaultProject: ProjectConfig = {
  name: 'Budynek magazynowo-biurowy',
  buildingType: 'Magazyn z częścią biurową',
  warehouseAreaM2: 3000,
  warehouseHeightM: 8,
  officeAreaM2: 450,
  peopleCount: 35,
  computerCount: 32,
  minWarehouseTempC: 8,
  maxWarehouseTempC: 28,
  minOfficeTempC: 20,
  maxOfficeTempC: 26,
  reservePercent: 15,
  useAlternativeHeatingCooling: true,
  normalHvacDeratingFactor: 0.65,
  zones: [
    {
      id: 'warehouse',
      name: 'Magazyn',
      type: 'warehouse',
      areaM2: 3000,
      heightM: 8,
      minTempC: 8,
      maxTempC: 28,
    },
    {
      id: 'office',
      name: 'Biuro',
      type: 'office',
      areaM2: 450,
      heightM: 3,
      minTempC: 20,
      maxTempC: 26,
    },
    {
      id: 'server-room',
      name: 'Serwerownia',
      type: 'serverRoom',
      areaM2: 20,
      minTempC: 18,
      maxTempC: 24,
    },
    {
      id: 'technical',
      name: 'Pomieszczenia techniczne',
      type: 'technical',
      areaM2: 60,
      minTempC: 10,
      maxTempC: 30,
    },
  ],
  energyStorage: {
    enabled: true,
    capacityKwh: 120,
    chargePowerKw: 50,
    dischargePowerKw: 50,
    mode: 'peakShaving',
    roundTripEfficiencyPercent: 92,
  },
}

export const defaultDevices: Device[] = [
  {
    id: 'device-heat-pump-warehouse',
    name: 'Pompa ciepła magazynu',
    categoryId: 'heatPumps',
    zoneId: 'warehouse',
    powerInputMode: 'area',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 56,
    powerDensityWm2: 2.25,
    thermalDensityUnit: 'Wm3',
    copMinus20C: defaultHeatPumpCopMinus20C,
    copNormal: defaultHeatPumpCopNormal,
    simultaneityFactor: 0.9,
    utilizationFactor: 0.85,
    cosPhi: 0.92,
    phase: '3P',
    voltageV: 400,
    scenarios: ['winter'],
    notes: 'Moc cieplna: kubatura magazynu × W/m³, moc elektryczna = ciepło / COP(-20°C). Scenariusz zimowy.',
  },
  {
    id: 'device-heat-pump-office',
    name: 'Pompa ciepła biura',
    categoryId: 'heatPumps',
    zoneId: 'office',
    powerInputMode: 'area',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 18,
    powerDensityWm2: 40,
    thermalDensityUnit: 'Wm2',
    copMinus20C: defaultHeatPumpCopMinus20C,
    copNormal: defaultHeatPumpCopNormal,
    simultaneityFactor: 0.9,
    utilizationFactor: 0.85,
    cosPhi: 0.92,
    phase: '3P',
    voltageV: 400,
    scenarios: ['winter'],
    notes: 'Moc cieplna z W/m2, moc elektryczna = ciepło / COP(-20°C). Scenariusz zimowy.',
  },
  {
    id: 'device-office-ac',
    name: 'Klimatyzacja biur',
    categoryId: 'cooling',
    zoneId: 'office',
    powerInputMode: 'area',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 21,
    powerDensityWm2: 45,
    copMinus20C: defaultHeatPumpCopMinus20C,
    copNormal: defaultHeatPumpCopNormal,
    simultaneityFactor: 0.8,
    utilizationFactor: 0.8,
    cosPhi: 0.9,
    phase: '1P',
    voltageV: 230,
    scenarios: ['summer'],
    notes: 'Moc chłodnicza z W/m2, moc elektryczna = chłód / COP(-20°C). Scenariusz letni.',
  },
  {
    id: 'device-office-cwu',
    name: 'CWU — ciepła woda biura',
    categoryId: 'cwu',
    zoneId: 'office',
    powerInputMode: 'area',
    quantityInputMode: 'people',
    quantity: 1,
    unitPowerKw: 5,
    powerDensityWm2: defaultCwuThermalDensityWPerPerson,
    copMinus20C: defaultHeatPumpCopMinus20C,
    copNormal: defaultHeatPumpCopNormal,
    simultaneityFactor: 0.7,
    utilizationFactor: 0.65,
    cosPhi: 0.92,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter'],
    notes: 'Moc cieplna: liczba osób × W/os., moc elektryczna = ciepło / COP(-20°C).',
  },
  {
    id: 'device-ahu',
    name: 'Centrale wentylacyjne',
    categoryId: 'ventilation',
    zoneId: 'technical',
    powerInputMode: 'manual',
    quantityInputMode: 'manual',
    quantity: 2,
    unitPowerKw: 12,
    simultaneityFactor: 0.95,
    utilizationFactor: 0.9,
    cosPhi: 0.88,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer', 'backup'],
  },
  {
    id: 'device-led-warehouse',
    name: 'Oświetlenie LED magazynu',
    categoryId: 'lighting',
    zoneId: 'warehouse',
    powerInputMode: 'area',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 24,
    powerDensityWm2: 8,
    simultaneityFactor: 0.85,
    utilizationFactor: 0.75,
    cosPhi: 0.95,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer', 'backup'],
  },
  {
    id: 'device-server-room',
    name: 'Serwerownia i UPS',
    categoryId: 'serverRoom',
    zoneId: 'server-room',
    powerInputMode: 'manual',
    quantityInputMode: 'manual',
    quantity: 1,
    unitPowerKw: 18,
    simultaneityFactor: 1,
    utilizationFactor: 0.9,
    cosPhi: 0.95,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer', 'backup'],
  },
  {
    id: 'device-dock-equipment',
    name: 'Bramy i urządzenia dokowe',
    categoryId: 'technology',
    zoneId: 'warehouse',
    powerInputMode: 'manual',
    quantityInputMode: 'manual',
    quantity: 8,
    unitPowerKw: 1.5,
    simultaneityFactor: 0.45,
    utilizationFactor: 0.7,
    cosPhi: 0.85,
    phase: '3P',
    voltageV: 400,
    scenarios: ['normal', 'winter', 'summer'],
  },
  {
    id: 'device-office-computers',
    name: 'Komputery stanowiskowe',
    categoryId: 'sockets',
    zoneId: 'office',
    powerInputMode: 'manual',
    quantityInputMode: 'computers',
    quantity: 32,
    unitPowerKw: 0.18,
    simultaneityFactor: 0.8,
    utilizationFactor: 0.7,
    cosPhi: 0.95,
    phase: '1P',
    voltageV: 230,
    scenarios: ['normal', 'summer', 'backup'],
    notes: 'Ilość pobierana z parametru liczby komputerów w projekcie.',
  },
  {
    id: 'device-workstations-sockets',
    name: 'Gniazda stanowisk pracy',
    categoryId: 'sockets',
    zoneId: 'office',
    powerInputMode: 'manual',
    quantityInputMode: 'people',
    quantity: 35,
    unitPowerKw: 0.12,
    simultaneityFactor: 0.55,
    utilizationFactor: 0.65,
    cosPhi: 0.95,
    phase: '1P',
    voltageV: 230,
    scenarios: ['normal', 'summer'],
    notes: 'Ilość pobierana z parametru liczby osób pracujących.',
  },
]
